  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  spring:
    cloud:
      config:
        override-system-properties: false # i dont want to override specific properties from .yml services

  management:
    tracing:
      sampling:
        probability: 1.0
