spring:
  data:
    mongodb:
      username: siberian
      password: siberian
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,OrderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:gr.siberian.ecommerce.kafka.OrderConfirmation,paymentConfirmation:gr.siberian.ecommerce.dto.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      smtp:
        trust: "*"
      authentication: true
      starttls:
        enabled: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000

  server:
    port: 8040
